feat: allow for registry override [WIP]
paritytech/asset-transfer-api pull request #369
Opened 2024-02-09 15:47 UTC by bee344

2024-02-12 20:25 UTC, marshacb commented on src/registry/parseRegistry.spec.ts
> +	it("Should correctly override the registry's token entry", () => {
duplicate test case

2024-02-12 20:28 UTC, marshacb approved these changes
minor nit. LGTM

2024-02-13 00:29 UTC, TarikGul commented on src/types.ts
> +	overridingRegistry?: RequireAtLeastOne<ChainInfoRegistry<InjectedChainInfoKeys>>;
To keep things in the active tense, I think we should call this `overrideRegistry`.

2024-02-13 00:33 UTC, TarikGul requested changes
Overall looks amazing! Small nit, I think we should change the name to `overrideRegistry`. In addition to that we need to update the docs in the README.md that go over the `AssetTransferApiOpts`.

2024-02-13 15:55 UTC, TarikGul approved these changes
LGTM, great job :)

2024-02-16 14:42 UTC, merged

2024-03-08 08:10 UTC, Polkadot-Forum commented
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/parity-tech-update-for-february/6630/1